# Generated by Django 3.2.5 on 2021-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(db_column='TicketID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('flightid', models.CharField(blank=True, db_column='FlightID', max_length=11, null=True)),
                ('airportid', models.IntegerField(blank=True, db_column='AirportID', null=True)),
                ('money', models.CharField(blank=True, db_column='Money', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.CharField(db_column='FlightID', max_length=30, primary_key=True, serialize=False)),
                ('planeid', models.IntegerField(blank=True, db_column='PlaneID', null=True)),
                ('flightname', models.CharField(blank=True, db_column='FlightName', max_length=255, null=True)),
                ('utime', models.DateTimeField(blank=True, db_column='UTime', null=True)),
                ('dtime', models.DateTimeField(blank=True, db_column='DTime', null=True)),
                ('origin', models.CharField(blank=True, db_column='Origin', max_length=255, null=True)),
                ('destination', models.CharField(blank=True, db_column='Destination', max_length=255, null=True)),
                ('isdelay', models.CharField(blank=True, db_column='IsDelay', max_length=255, null=True)),
                ('seatleft', models.IntegerField(blank=True, db_column='SeatLeft', null=True)),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
    ]
