# Generated by Django 3.2.5 on 2021-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='User', max_length=255, null=True)),
                ('userage', models.CharField(blank=True, db_column='UserAge', max_length=255, null=True)),
                ('useridentity', models.CharField(blank=True, db_column='UserIdentity', max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
